#8 Add Toppings, Pizzas to the Lists
MachOneSoftware/PizzaBuddy pull request #19
Opened 2019-10-21 22:50 UTC by jordihereu

- Adding 2 new pizzas, 5 new toppings
- Fixing compilation error (replace wrong {} by [] next to Hawaiian Elvis pizza)

2019-10-27 01:59 UTC, javajudt requested changes
Just noticed a couple minor typos, otherwise good!

2019-10-27 01:59 UTC, javajudt commented on Repo.cs
> +                "parmegian",
```suggestion
                "parmigian",
```

2019-10-27 01:59 UTC, javajudt commented on Repo.cs
> +                { "Four cheese",        new[] {"riccota","parmegian","mozzarella","gorgonzola" } }
```suggestion
                { "Four cheese",        new[] {"riccota","parmigian","mozzarella","gorgonzola" } }
```

2019-10-28 14:55 UTC, jordihereu commented
OK, I´ve applied the PR feedback. It´s the first time I´m solving conflicts in a GitHub branch so I did my best. I don´t know if I did it the best possible way. Anyway I think my changes are there to be reviewed.
Thanks.

2019-10-29 04:31 UTC, javajudt approved these changes
Looks good! Thanks!

2019-10-29 04:32 UTC, merged